from typing import Callable, Union, List


def http(main_func: Union[Callable, List[Callable]] = None, verify_token: str = None, app_secret_key: str = None):
    ...


class HttpApi:
    def __init__(self, verify_token: str, app_secret_key: str = None) -> None:
        self.text_handlers: List[Callable] = ...
        self.attachment_handlers: List[Callable] = ...
        self.postback_handlers: List[Callable] = ...
        self.verify_token: str = ...
        self.app_secret_key: str = ...
        self.app = ...

    def add_text_handler(self, func: Callable, text: str = None, position: str = None) -> None:
        ...

    def add_attachment_handler(self, func: Callable, attachment_type: str = None):
        ...

    def add_postback_handler(self, func: Callable) -> None:
        ...

    def dispatch_handlers(self, message) -> None:
        ...
